@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.value.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Rafael Veiga ",
  "email": "rafaelVeiga@gmail.com",
  "password": "12345678"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "rafaelVeiga@gmail.com",
  "password": "12345678"
}

###
# @name create_category
POST {{baseUrl}}/categories
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "carr",
  "description": "Despesas com serviços de gastos com o meu veiculo"
}
###
# @name create_budget
POST {{baseUrl}}/budgets
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "amount": 520,
  "categoryId": "b6f462d7-1a37-4ab6-a978-4f628b24b5bb",
  "startDate": "2024-05-10",
  "endDate": "2024-06-10"
}

###
# @name create_incomes
POST {{baseUrl}}/incomes
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "amount": 2000,
  "description": "Freelance",
  "categoryId": "4e4b4172-a0b2-479a-b6f8-05c7e8b84aba"
}

###
# @name create_expenses
POST {{baseUrl}}/expense
Content-Type: application/json
Authorization: Bearer {{authToken}}


{
  "amount": 13.90,
  "description": "Assinatura Netflix",
  "categoryId": "a11e4ce4-6d47-421d-8021-840577816bec",
  "date": "2024-05-10"
}

###
# @name edit_category
PUT  {{baseUrl}}/categories/ef8bf265-4951-45f6-8e98-59ce24425a20
Content-Type: application/json

{
  "name": "Carro",
  "description": "Despesas com serviços de gastos com o meu veiculo"
}

###
# @name delete_category
DELETE  {{baseUrl}}/categories/884b7ad9-8e08-4c92-ac69-5b20da573cb0
Content-Type: application/json


###
# @name delete_budgets
DELETE  {{baseUrl}}/budgets/b480b05e-16d5-4892-963e-5c703845f9df
Content-Type: application/json
Authorization: Bearer {{authToken}}

###
# @name delete_expenses
DELETE  {{baseUrl}}/expenses/76f4904f-2af1-4eab-b4da-e75d6090d6cd
Content-Type: application/json
Authorization: Bearer {{authToken}}

###
# @name edit_expenses
PUT  {{baseUrl}}/expenses/b2f6c44e-544b-45f2-81b3-8df84cbe8982
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "amount": 23.99,
  "date": "2024-05-10",
  "categoryId": "a11e4ce4-6d47-421d-8021-840577816bec"
}
