version: '3.9'

services:
  postgres:
    image: postgres
    restart: always
    container_name: finance-wise-pg
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: finance-wise
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
